package com.android.okhttp.monitor.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.okhttp.monitor.db.MonitorData;

import com.android.okhttp.monitor.db.MonitorDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig monitorDataDaoConfig;

    private final MonitorDataDao monitorDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        monitorDataDaoConfig = daoConfigMap.get(MonitorDataDao.class).clone();
        monitorDataDaoConfig.initIdentityScope(type);

        monitorDataDao = new MonitorDataDao(monitorDataDaoConfig, this);

        registerDao(MonitorData.class, monitorDataDao);
    }
    
    public void clear() {
        monitorDataDaoConfig.clearIdentityScope();
    }

    public MonitorDataDao getMonitorDataDao() {
        return monitorDataDao;
    }

}
